/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.foursquare.twofishes;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

// No additional import required for struct/union.

public class BulkReverseGeocodeResponse implements TBase<BulkReverseGeocodeResponse, BulkReverseGeocodeResponse._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("BulkReverseGeocodeResponse");

  private static final TField INTERPRETATIONS_FIELD_DESC = new TField("interpretations", TType.LIST, (short)1);
  private static final TField LATLNG_TO_INTERPRETATION_MAP_FIELD_DESC = new TField("latlngToInterpretationMap", TType.MAP, (short)2);
  private static final TField DEBUG_LINES_FIELD_DESC = new TField("debugLines", TType.LIST, (short)3);

  public List<GeocodeInterpretation> interpretations;
  public Map<Integer,List<Integer>> latlngToInterpretationMap;
  public List<String> debugLines;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    INTERPRETATIONS((short)1, "interpretations"),
    LATLNG_TO_INTERPRETATION_MAP((short)2, "latlngToInterpretationMap"),
    DEBUG_LINES((short)3, "debugLines");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTERPRETATIONS
          return INTERPRETATIONS;
        case 2: // LATLNG_TO_INTERPRETATION_MAP
          return LATLNG_TO_INTERPRETATION_MAP;
        case 3: // DEBUG_LINES
          return DEBUG_LINES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTERPRETATIONS, new FieldMetaData("interpretations", TFieldRequirementType.REQUIRED, 
        new ListMetaData(TType.LIST, 
            new StructMetaData(TType.STRUCT, GeocodeInterpretation.class))));
    tmpMap.put(_Fields.LATLNG_TO_INTERPRETATION_MAP, new FieldMetaData("latlngToInterpretationMap", TFieldRequirementType.REQUIRED, 
        new MapMetaData(TType.MAP, 
            new FieldValueMetaData(TType.I32), 
            new ListMetaData(TType.LIST, 
                new FieldValueMetaData(TType.I32)))));
    tmpMap.put(_Fields.DEBUG_LINES, new FieldMetaData("debugLines", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(BulkReverseGeocodeResponse.class, metaDataMap);
  }

  public BulkReverseGeocodeResponse() {
  }

  public BulkReverseGeocodeResponse(
    List<GeocodeInterpretation> interpretations,
    Map<Integer,List<Integer>> latlngToInterpretationMap)
  {
    this();
    this.interpretations = interpretations;
    this.latlngToInterpretationMap = latlngToInterpretationMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BulkReverseGeocodeResponse(BulkReverseGeocodeResponse other) {
    if (other.isSetInterpretations()) {
      List<GeocodeInterpretation> __this__interpretations = new ArrayList<GeocodeInterpretation>();
      for (GeocodeInterpretation other_element : other.interpretations) {
        __this__interpretations.add(new GeocodeInterpretation(other_element));
      }
      this.interpretations = __this__interpretations;
    }
    if (other.isSetLatlngToInterpretationMap()) {
      Map<Integer,List<Integer>> __this__latlngToInterpretationMap = new HashMap<Integer,List<Integer>>();
      for (Map.Entry<Integer, List<Integer>> other_element : other.latlngToInterpretationMap.entrySet()) {

        Integer other_element_key = other_element.getKey();
        List<Integer> other_element_value = other_element.getValue();

        Integer __this__latlngToInterpretationMap_copy_key = other_element_key;

        List<Integer> __this__latlngToInterpretationMap_copy_value = new ArrayList<Integer>();
        for (Integer other_element_value_element : other_element_value) {
          __this__latlngToInterpretationMap_copy_value.add(other_element_value_element);
        }

        __this__latlngToInterpretationMap.put(__this__latlngToInterpretationMap_copy_key, __this__latlngToInterpretationMap_copy_value);
      }
      this.latlngToInterpretationMap = __this__latlngToInterpretationMap;
    }
    if (other.isSetDebugLines()) {
      List<String> __this__debugLines = new ArrayList<String>();
      for (String other_element : other.debugLines) {
        __this__debugLines.add(other_element);
      }
      this.debugLines = __this__debugLines;
    }
  }

  public BulkReverseGeocodeResponse deepCopy() {
    return new BulkReverseGeocodeResponse(this);
  }

  @Override
  public void clear() {
    this.interpretations = null;
    this.latlngToInterpretationMap = null;
    this.debugLines = null;
  }

  public int getInterpretationsSize() {
    return (this.interpretations == null) ? 0 : this.interpretations.size();
  }

  public java.util.Iterator<GeocodeInterpretation> getInterpretationsIterator() {
    return (this.interpretations == null) ? null : this.interpretations.iterator();
  }

  public void addToInterpretations(GeocodeInterpretation elem) {
    if (this.interpretations == null) {
      this.interpretations = new ArrayList<GeocodeInterpretation>();
    }
    this.interpretations.add(elem);
  }

  public List<GeocodeInterpretation> getInterpretations() {
    return this.interpretations;
  }

  public BulkReverseGeocodeResponse setInterpretations(List<GeocodeInterpretation> interpretations) {
    this.interpretations = interpretations;
    return this;
  }

  public void unsetInterpretations() {
    this.interpretations = null;
  }

  /** Returns true if field interpretations is set (has been asigned a value) and false otherwise */
  public boolean isSetInterpretations() {
    return this.interpretations != null;
  }

  public void setInterpretationsIsSet(boolean value) {
    if (!value) {
      this.interpretations = null;
    }
  }

  public int getLatlngToInterpretationMapSize() {
    return (this.latlngToInterpretationMap == null) ? 0 : this.latlngToInterpretationMap.size();
  }

  public void putToLatlngToInterpretationMap(int key, List<Integer> val) {
    if (this.latlngToInterpretationMap == null) {
      this.latlngToInterpretationMap = new HashMap<Integer,List<Integer>>();
    }
    this.latlngToInterpretationMap.put(key, val);
  }

  public Map<Integer,List<Integer>> getLatlngToInterpretationMap() {
    return this.latlngToInterpretationMap;
  }

  public BulkReverseGeocodeResponse setLatlngToInterpretationMap(Map<Integer,List<Integer>> latlngToInterpretationMap) {
    this.latlngToInterpretationMap = latlngToInterpretationMap;
    return this;
  }

  public void unsetLatlngToInterpretationMap() {
    this.latlngToInterpretationMap = null;
  }

  /** Returns true if field latlngToInterpretationMap is set (has been asigned a value) and false otherwise */
  public boolean isSetLatlngToInterpretationMap() {
    return this.latlngToInterpretationMap != null;
  }

  public void setLatlngToInterpretationMapIsSet(boolean value) {
    if (!value) {
      this.latlngToInterpretationMap = null;
    }
  }

  public int getDebugLinesSize() {
    return (this.debugLines == null) ? 0 : this.debugLines.size();
  }

  public java.util.Iterator<String> getDebugLinesIterator() {
    return (this.debugLines == null) ? null : this.debugLines.iterator();
  }

  public void addToDebugLines(String elem) {
    if (this.debugLines == null) {
      this.debugLines = new ArrayList<String>();
    }
    this.debugLines.add(elem);
  }

  public List<String> getDebugLines() {
    return this.debugLines;
  }

  public BulkReverseGeocodeResponse setDebugLines(List<String> debugLines) {
    this.debugLines = debugLines;
    return this;
  }

  public void unsetDebugLines() {
    this.debugLines = null;
  }

  /** Returns true if field debugLines is set (has been asigned a value) and false otherwise */
  public boolean isSetDebugLines() {
    return this.debugLines != null;
  }

  public void setDebugLinesIsSet(boolean value) {
    if (!value) {
      this.debugLines = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INTERPRETATIONS:
      if (value == null) {
        unsetInterpretations();
      } else {
        setInterpretations((List<GeocodeInterpretation>)value);
      }
      break;

    case LATLNG_TO_INTERPRETATION_MAP:
      if (value == null) {
        unsetLatlngToInterpretationMap();
      } else {
        setLatlngToInterpretationMap((Map<Integer,List<Integer>>)value);
      }
      break;

    case DEBUG_LINES:
      if (value == null) {
        unsetDebugLines();
      } else {
        setDebugLines((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INTERPRETATIONS:
      return getInterpretations();

    case LATLNG_TO_INTERPRETATION_MAP:
      return getLatlngToInterpretationMap();

    case DEBUG_LINES:
      return getDebugLines();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INTERPRETATIONS:
      return isSetInterpretations();
    case LATLNG_TO_INTERPRETATION_MAP:
      return isSetLatlngToInterpretationMap();
    case DEBUG_LINES:
      return isSetDebugLines();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BulkReverseGeocodeResponse)
      return this.equals((BulkReverseGeocodeResponse)that);
    return false;
  }

  public boolean equals(BulkReverseGeocodeResponse that) {
    if (that == null)
      return false;

    boolean this_present_interpretations = true && this.isSetInterpretations();
    boolean that_present_interpretations = true && that.isSetInterpretations();
    if (this_present_interpretations || that_present_interpretations) {
      if (!(this_present_interpretations && that_present_interpretations))
        return false;
      if (!this.interpretations.equals(that.interpretations))
        return false;
    }

    boolean this_present_latlngToInterpretationMap = true && this.isSetLatlngToInterpretationMap();
    boolean that_present_latlngToInterpretationMap = true && that.isSetLatlngToInterpretationMap();
    if (this_present_latlngToInterpretationMap || that_present_latlngToInterpretationMap) {
      if (!(this_present_latlngToInterpretationMap && that_present_latlngToInterpretationMap))
        return false;
      if (!this.latlngToInterpretationMap.equals(that.latlngToInterpretationMap))
        return false;
    }

    boolean this_present_debugLines = true && this.isSetDebugLines();
    boolean that_present_debugLines = true && that.isSetDebugLines();
    if (this_present_debugLines || that_present_debugLines) {
      if (!(this_present_debugLines && that_present_debugLines))
        return false;
      if (!this.debugLines.equals(that.debugLines))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(BulkReverseGeocodeResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    BulkReverseGeocodeResponse typedOther = (BulkReverseGeocodeResponse)other;

    lastComparison = Boolean.valueOf(isSetInterpretations()).compareTo(typedOther.isSetInterpretations());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInterpretations()) {
      lastComparison = TBaseHelper.compareTo(this.interpretations, typedOther.interpretations);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLatlngToInterpretationMap()).compareTo(typedOther.isSetLatlngToInterpretationMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatlngToInterpretationMap()) {
      lastComparison = TBaseHelper.compareTo(this.latlngToInterpretationMap, typedOther.latlngToInterpretationMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDebugLines()).compareTo(typedOther.isSetDebugLines());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDebugLines()) {
      lastComparison = TBaseHelper.compareTo(this.debugLines, typedOther.debugLines);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // INTERPRETATIONS
          if (field.type == TType.LIST) {
            {
              TList _list80 = iprot.readListBegin();
              this.interpretations = new ArrayList<GeocodeInterpretation>(_list80.size);
              for (int _i81 = 0; _i81 < _list80.size; ++_i81)
              {
                GeocodeInterpretation _elem82;
                _elem82 = new GeocodeInterpretation();
                _elem82.read(iprot);
                this.interpretations.add(_elem82);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // LATLNG_TO_INTERPRETATION_MAP
          if (field.type == TType.MAP) {
            {
              TMap _map83 = iprot.readMapBegin();
              this.latlngToInterpretationMap = new HashMap<Integer,List<Integer>>(2*_map83.size);
              for (int _i84 = 0; _i84 < _map83.size; ++_i84)
              {
                int _key85;
                List<Integer> _val86;
                _key85 = iprot.readI32();
                {
                  TList _list87 = iprot.readListBegin();
                  _val86 = new ArrayList<Integer>(_list87.size);
                  for (int _i88 = 0; _i88 < _list87.size; ++_i88)
                  {
                    int _elem89;
                    _elem89 = iprot.readI32();
                    _val86.add(_elem89);
                  }
                  iprot.readListEnd();
                }
                this.latlngToInterpretationMap.put(_key85, _val86);
              }
              iprot.readMapEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // DEBUG_LINES
          if (field.type == TType.LIST) {
            {
              TList _list90 = iprot.readListBegin();
              this.debugLines = new ArrayList<String>(_list90.size);
              for (int _i91 = 0; _i91 < _list90.size; ++_i91)
              {
                String _elem92;
                _elem92 = iprot.readString();
                this.debugLines.add(_elem92);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.interpretations != null) {
      oprot.writeFieldBegin(INTERPRETATIONS_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.interpretations.size()));
        for (GeocodeInterpretation _iter93 : this.interpretations)
        {
          _iter93.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.latlngToInterpretationMap != null) {
      oprot.writeFieldBegin(LATLNG_TO_INTERPRETATION_MAP_FIELD_DESC);
      {
        oprot.writeMapBegin(new TMap(TType.I32, TType.LIST, this.latlngToInterpretationMap.size()));
        for (Map.Entry<Integer, List<Integer>> _iter94 : this.latlngToInterpretationMap.entrySet())
        {
          oprot.writeI32(_iter94.getKey());
          {
            oprot.writeListBegin(new TList(TType.I32, _iter94.getValue().size()));
            for (int _iter95 : _iter94.getValue())
            {
              oprot.writeI32(_iter95);
            }
            oprot.writeListEnd();
          }
        }
        oprot.writeMapEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.debugLines != null) {
      if (isSetDebugLines()) {
        oprot.writeFieldBegin(DEBUG_LINES_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.debugLines.size()));
          for (String _iter96 : this.debugLines)
          {
            oprot.writeString(_iter96);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BulkReverseGeocodeResponse(");
    boolean first = true;

    sb.append("interpretations:");
    if (this.interpretations == null) {
      sb.append("null");
    } else {
      sb.append(this.interpretations);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("latlngToInterpretationMap:");
    if (this.latlngToInterpretationMap == null) {
      sb.append("null");
    } else {
      sb.append(this.latlngToInterpretationMap);
    }
    first = false;
    if (isSetDebugLines()) {
      if (!first) sb.append(", ");
      sb.append("debugLines:");
      if (this.debugLines == null) {
        sb.append("null");
      } else {
        sb.append(this.debugLines);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (interpretations == null) {
      throw new TProtocolException("Required field 'interpretations' was not present! Struct: " + toString());
    }
    if (latlngToInterpretationMap == null) {
      throw new TProtocolException("Required field 'latlngToInterpretationMap' was not present! Struct: " + toString());
    }
  }

}

