/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.foursquare.twofishes;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FeatureNameFlags implements TEnum {
  PREFERRED(1),
  ABBREVIATION(2),
  DEACCENT(4),
  ALIAS(8),
  LOCAL_LANG(16),
  ALT_NAME(32),
  COLLOQUIAL(64);

  private final int value;

  private FeatureNameFlags(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FeatureNameFlags findByValue(int value) { 
    switch (value) {
      case 1:
        return PREFERRED;
      case 2:
        return ABBREVIATION;
      case 4:
        return DEACCENT;
      case 8:
        return ALIAS;
      case 16:
        return LOCAL_LANG;
      case 32:
        return ALT_NAME;
      case 64:
        return COLLOQUIAL;
      default:
        return null;
    }
  }
}
