/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.foursquare.twofishes;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

// No additional import required for struct/union.

public class GeocodeInterpretation implements TBase<GeocodeInterpretation, GeocodeInterpretation._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("GeocodeInterpretation");

  private static final TField WHAT_FIELD_DESC = new TField("what", TType.STRING, (short)1);
  private static final TField WHERE_FIELD_DESC = new TField("where", TType.STRING, (short)2);
  private static final TField FEATURE_FIELD_DESC = new TField("feature", TType.STRUCT, (short)3);
  private static final TField PARENTS_FIELD_DESC = new TField("parents", TType.LIST, (short)4);
  private static final TField SCORING_FEATURES_FIELD_DESC = new TField("scoringFeatures", TType.STRUCT, (short)5);

  public String what;
  public String where;
  public GeocodeFeature feature;
  public List<GeocodeFeature> parents;
  public ScoringFeatures scoringFeatures;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    WHAT((short)1, "what"),
    WHERE((short)2, "where"),
    FEATURE((short)3, "feature"),
    PARENTS((short)4, "parents"),
    SCORING_FEATURES((short)5, "scoringFeatures");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WHAT
          return WHAT;
        case 2: // WHERE
          return WHERE;
        case 3: // FEATURE
          return FEATURE;
        case 4: // PARENTS
          return PARENTS;
        case 5: // SCORING_FEATURES
          return SCORING_FEATURES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WHAT, new FieldMetaData("what", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.WHERE, new FieldMetaData("where", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.FEATURE, new FieldMetaData("feature", TFieldRequirementType.DEFAULT, 
        new StructMetaData(TType.STRUCT, GeocodeFeature.class)));
    tmpMap.put(_Fields.PARENTS, new FieldMetaData("parents", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new StructMetaData(TType.STRUCT, GeocodeFeature.class))));
    tmpMap.put(_Fields.SCORING_FEATURES, new FieldMetaData("scoringFeatures", TFieldRequirementType.OPTIONAL, 
        new StructMetaData(TType.STRUCT, ScoringFeatures.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(GeocodeInterpretation.class, metaDataMap);
  }

  public GeocodeInterpretation() {
  }

  public GeocodeInterpretation(
    String what,
    String where,
    GeocodeFeature feature)
  {
    this();
    this.what = what;
    this.where = where;
    this.feature = feature;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GeocodeInterpretation(GeocodeInterpretation other) {
    if (other.isSetWhat()) {
      this.what = other.what;
    }
    if (other.isSetWhere()) {
      this.where = other.where;
    }
    if (other.isSetFeature()) {
      this.feature = new GeocodeFeature(other.feature);
    }
    if (other.isSetParents()) {
      List<GeocodeFeature> __this__parents = new ArrayList<GeocodeFeature>();
      for (GeocodeFeature other_element : other.parents) {
        __this__parents.add(new GeocodeFeature(other_element));
      }
      this.parents = __this__parents;
    }
    if (other.isSetScoringFeatures()) {
      this.scoringFeatures = new ScoringFeatures(other.scoringFeatures);
    }
  }

  public GeocodeInterpretation deepCopy() {
    return new GeocodeInterpretation(this);
  }

  @Override
  public void clear() {
    this.what = null;
    this.where = null;
    this.feature = null;
    this.parents = null;
    this.scoringFeatures = null;
  }

  public String getWhat() {
    return this.what;
  }

  public GeocodeInterpretation setWhat(String what) {
    this.what = what;
    return this;
  }

  public void unsetWhat() {
    this.what = null;
  }

  /** Returns true if field what is set (has been asigned a value) and false otherwise */
  public boolean isSetWhat() {
    return this.what != null;
  }

  public void setWhatIsSet(boolean value) {
    if (!value) {
      this.what = null;
    }
  }

  public String getWhere() {
    return this.where;
  }

  public GeocodeInterpretation setWhere(String where) {
    this.where = where;
    return this;
  }

  public void unsetWhere() {
    this.where = null;
  }

  /** Returns true if field where is set (has been asigned a value) and false otherwise */
  public boolean isSetWhere() {
    return this.where != null;
  }

  public void setWhereIsSet(boolean value) {
    if (!value) {
      this.where = null;
    }
  }

  public GeocodeFeature getFeature() {
    return this.feature;
  }

  public GeocodeInterpretation setFeature(GeocodeFeature feature) {
    this.feature = feature;
    return this;
  }

  public void unsetFeature() {
    this.feature = null;
  }

  /** Returns true if field feature is set (has been asigned a value) and false otherwise */
  public boolean isSetFeature() {
    return this.feature != null;
  }

  public void setFeatureIsSet(boolean value) {
    if (!value) {
      this.feature = null;
    }
  }

  public int getParentsSize() {
    return (this.parents == null) ? 0 : this.parents.size();
  }

  public java.util.Iterator<GeocodeFeature> getParentsIterator() {
    return (this.parents == null) ? null : this.parents.iterator();
  }

  public void addToParents(GeocodeFeature elem) {
    if (this.parents == null) {
      this.parents = new ArrayList<GeocodeFeature>();
    }
    this.parents.add(elem);
  }

  public List<GeocodeFeature> getParents() {
    return this.parents;
  }

  public GeocodeInterpretation setParents(List<GeocodeFeature> parents) {
    this.parents = parents;
    return this;
  }

  public void unsetParents() {
    this.parents = null;
  }

  /** Returns true if field parents is set (has been asigned a value) and false otherwise */
  public boolean isSetParents() {
    return this.parents != null;
  }

  public void setParentsIsSet(boolean value) {
    if (!value) {
      this.parents = null;
    }
  }

  public ScoringFeatures getScoringFeatures() {
    return this.scoringFeatures;
  }

  public GeocodeInterpretation setScoringFeatures(ScoringFeatures scoringFeatures) {
    this.scoringFeatures = scoringFeatures;
    return this;
  }

  public void unsetScoringFeatures() {
    this.scoringFeatures = null;
  }

  /** Returns true if field scoringFeatures is set (has been asigned a value) and false otherwise */
  public boolean isSetScoringFeatures() {
    return this.scoringFeatures != null;
  }

  public void setScoringFeaturesIsSet(boolean value) {
    if (!value) {
      this.scoringFeatures = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case WHAT:
      if (value == null) {
        unsetWhat();
      } else {
        setWhat((String)value);
      }
      break;

    case WHERE:
      if (value == null) {
        unsetWhere();
      } else {
        setWhere((String)value);
      }
      break;

    case FEATURE:
      if (value == null) {
        unsetFeature();
      } else {
        setFeature((GeocodeFeature)value);
      }
      break;

    case PARENTS:
      if (value == null) {
        unsetParents();
      } else {
        setParents((List<GeocodeFeature>)value);
      }
      break;

    case SCORING_FEATURES:
      if (value == null) {
        unsetScoringFeatures();
      } else {
        setScoringFeatures((ScoringFeatures)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case WHAT:
      return getWhat();

    case WHERE:
      return getWhere();

    case FEATURE:
      return getFeature();

    case PARENTS:
      return getParents();

    case SCORING_FEATURES:
      return getScoringFeatures();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case WHAT:
      return isSetWhat();
    case WHERE:
      return isSetWhere();
    case FEATURE:
      return isSetFeature();
    case PARENTS:
      return isSetParents();
    case SCORING_FEATURES:
      return isSetScoringFeatures();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GeocodeInterpretation)
      return this.equals((GeocodeInterpretation)that);
    return false;
  }

  public boolean equals(GeocodeInterpretation that) {
    if (that == null)
      return false;

    boolean this_present_what = true && this.isSetWhat();
    boolean that_present_what = true && that.isSetWhat();
    if (this_present_what || that_present_what) {
      if (!(this_present_what && that_present_what))
        return false;
      if (!this.what.equals(that.what))
        return false;
    }

    boolean this_present_where = true && this.isSetWhere();
    boolean that_present_where = true && that.isSetWhere();
    if (this_present_where || that_present_where) {
      if (!(this_present_where && that_present_where))
        return false;
      if (!this.where.equals(that.where))
        return false;
    }

    boolean this_present_feature = true && this.isSetFeature();
    boolean that_present_feature = true && that.isSetFeature();
    if (this_present_feature || that_present_feature) {
      if (!(this_present_feature && that_present_feature))
        return false;
      if (!this.feature.equals(that.feature))
        return false;
    }

    boolean this_present_parents = true && this.isSetParents();
    boolean that_present_parents = true && that.isSetParents();
    if (this_present_parents || that_present_parents) {
      if (!(this_present_parents && that_present_parents))
        return false;
      if (!this.parents.equals(that.parents))
        return false;
    }

    boolean this_present_scoringFeatures = true && this.isSetScoringFeatures();
    boolean that_present_scoringFeatures = true && that.isSetScoringFeatures();
    if (this_present_scoringFeatures || that_present_scoringFeatures) {
      if (!(this_present_scoringFeatures && that_present_scoringFeatures))
        return false;
      if (!this.scoringFeatures.equals(that.scoringFeatures))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(GeocodeInterpretation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    GeocodeInterpretation typedOther = (GeocodeInterpretation)other;

    lastComparison = Boolean.valueOf(isSetWhat()).compareTo(typedOther.isSetWhat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhat()) {
      lastComparison = TBaseHelper.compareTo(this.what, typedOther.what);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWhere()).compareTo(typedOther.isSetWhere());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhere()) {
      lastComparison = TBaseHelper.compareTo(this.where, typedOther.where);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFeature()).compareTo(typedOther.isSetFeature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeature()) {
      lastComparison = TBaseHelper.compareTo(this.feature, typedOther.feature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParents()).compareTo(typedOther.isSetParents());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParents()) {
      lastComparison = TBaseHelper.compareTo(this.parents, typedOther.parents);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetScoringFeatures()).compareTo(typedOther.isSetScoringFeatures());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScoringFeatures()) {
      lastComparison = TBaseHelper.compareTo(this.scoringFeatures, typedOther.scoringFeatures);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // WHAT
          if (field.type == TType.STRING) {
            this.what = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // WHERE
          if (field.type == TType.STRING) {
            this.where = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // FEATURE
          if (field.type == TType.STRUCT) {
            this.feature = new GeocodeFeature();
            this.feature.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // PARENTS
          if (field.type == TType.LIST) {
            {
              TList _list28 = iprot.readListBegin();
              this.parents = new ArrayList<GeocodeFeature>(_list28.size);
              for (int _i29 = 0; _i29 < _list28.size; ++_i29)
              {
                GeocodeFeature _elem30;
                _elem30 = new GeocodeFeature();
                _elem30.read(iprot);
                this.parents.add(_elem30);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // SCORING_FEATURES
          if (field.type == TType.STRUCT) {
            this.scoringFeatures = new ScoringFeatures();
            this.scoringFeatures.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.what != null) {
      oprot.writeFieldBegin(WHAT_FIELD_DESC);
      oprot.writeString(this.what);
      oprot.writeFieldEnd();
    }
    if (this.where != null) {
      oprot.writeFieldBegin(WHERE_FIELD_DESC);
      oprot.writeString(this.where);
      oprot.writeFieldEnd();
    }
    if (this.feature != null) {
      oprot.writeFieldBegin(FEATURE_FIELD_DESC);
      this.feature.write(oprot);
      oprot.writeFieldEnd();
    }
    if (this.parents != null) {
      if (isSetParents()) {
        oprot.writeFieldBegin(PARENTS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRUCT, this.parents.size()));
          for (GeocodeFeature _iter31 : this.parents)
          {
            _iter31.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.scoringFeatures != null) {
      if (isSetScoringFeatures()) {
        oprot.writeFieldBegin(SCORING_FEATURES_FIELD_DESC);
        this.scoringFeatures.write(oprot);
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GeocodeInterpretation(");
    boolean first = true;

    sb.append("what:");
    if (this.what == null) {
      sb.append("null");
    } else {
      sb.append(this.what);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("where:");
    if (this.where == null) {
      sb.append("null");
    } else {
      sb.append(this.where);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("feature:");
    if (this.feature == null) {
      sb.append("null");
    } else {
      sb.append(this.feature);
    }
    first = false;
    if (isSetParents()) {
      if (!first) sb.append(", ");
      sb.append("parents:");
      if (this.parents == null) {
        sb.append("null");
      } else {
        sb.append(this.parents);
      }
      first = false;
    }
    if (isSetScoringFeatures()) {
      if (!first) sb.append(", ");
      sb.append("scoringFeatures:");
      if (this.scoringFeatures == null) {
        sb.append("null");
      } else {
        sb.append(this.scoringFeatures);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

